### ISSUE TITLE
Cannot build ServerAPI under Mac?

### ISSUE THREAD

**Issue by jasedit** [ECE4574-5574/ServerAPI#2]
I checked out the ServerAPI on my Macbook Pro, and opened the solution file using Xamarin. It opens the solution just fine, but when attempting to build I get the following error:

```
/Users/jpz/src/ece5574/ServerAPI/HomeAutomationServer/HomeAutomationServer.csproj: Error: This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=317567. (HomeAutomationServer)
```

I've followed the link, and attempted multiple builds, as well as commanding nuget to restore all the packages. Is there any way to build the system using a Mac, or failing that, some method for accessing the latest API documentation?

**Comment by Brian-Kaplan** [comment]
Maybe this will help?

http://5574serverapi.azurewebsites.net/Help

On Sun, Mar 29, 2015 at 4:36 PM, Jason Ziglar notifications@github.com
wrote:

> I checked out the ServerAPI on my Macbook Pro, and opened the solution
> file using Xamarin. It opens the solution just fine, but when attempting to
> build I get the following error:
> 
> /Users/jpz/src/ece5574/ServerAPI/HomeAutomationServer/HomeAutomationServer.csproj: Error: This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=317567. (HomeAutomationServer)
> 
> I've followed the link, and attempted multiple builds, as well as
> commanding nuget to restore all the packages. Is there any way to build the
> system using a Mac, or failing that, some method for accessing the latest
> API documentation?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ECE4574-5574/ServerAPI/issues/2.

## 

Sincerely,

Brian Kaplan

Computer Engineering 2016

703-336-3133

bakaplan2@gmail.com

**Comment by jasedit** [comment]
That definitely helps with providing a reference for the API. I still don't know if it's possible/how to build the API on my Mac - is that something I should be expecting to be able to do?

**Comment by Brian-Kaplan** [comment]
I'm not sure if you can build it and test locally. You can use postman to send requests to the server for testing. But the version we have up will not always be the most current. Unless you somehow get Visual Studio Community 2013 up on your mac I don't think you're going to be able to build it.

**Comment by jasedit** [comment]
So we won't be able to do local tests of the system on Macs? Or is this something that is future work?

**Comment by willrd9** [comment]
As far as I know the .NET API server cannot be locally tested on a Mac. However, using your favorite HTTP request generator (Fiddler, Postman) you will be able to soon use the OPTIONS request to determine proper formats for requests via the hosted server. This will help you develop/test your end of the system.

**Comment by ibalajiarun** [comment]
The project requires some native packages that are not available in Xamarin's mono framework. So, I do not think it will work on Mac very soon. Visual Studio 2013 is required.

**Comment by jasedit** [comment]
Quick question related to previous comments on this issue - when is the server API going to be deployed to the Amazon setup we're supposed to be using? Do we know the address of the server API we should be pointing our applications to by default?

**Comment by enghokie** [comment]
Are you referring to the persistent storage?

_Braedon Dickerson_
_Virginia Tech_
_Computer Engineering_
_Student Manager, West End Market_

**Comment by enghokie** [comment]
never mind, I think I misinterpreted what you were asking

_Braedon Dickerson_
_Virginia Tech_
_Computer Engineering_
_Student Manager, West End Market_

**Comment by jasedit** [comment]
My work is currently outside the server, so I can only talk to the server API, and is the server location I’m asking after.
